version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4596:4596"
    env_file:
      - .env
    volumes:
      - .:/app

networks:
  default:
    driver: bridge
