version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4596:4596"
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["npx", "concurrently", "npm:start", "node", "scripts/run-updater.js"]

networks:
  default:
    driver: bridge
